# Getting Started in the Lab {#getting_started}

Essential resources and steps

## Paperwork

See chapter 7 - Students

OK NEED TO FIGURE OUT WHAT WILL GO IN THIS SECTION - UNDERGRAD STUFF HERE OR IN CH 7?

CK - All of it here?? That way it's together, and then ch 7 can be just for grad students and include things like program requirements, the checklist, etc.??

### Undergraduate Students

There are two options for undergraduate RA's to get started with the lab; each RA only needs to choose one or the other. 




### Registration
Registering for Directed Independent Research (PSY4912) has the advantage of putting research on their transcript. We almost always register them for 0 credit hours so they can avoid paying tuition/fees, but they can take more if they need to fill out their schedule to reach full-time, keep a scholarship, etc. The [Restricted Registration Form](docs/resources/Undergraduate Registration Agreement Summer 2020.pdf) is filled out according to this template. IMPORTANT: Be sure the version you have is the most recent one (i.e., check with the program assistant, Mikala). 
1. Grad student fills out the term/course # (PSY4912) and the "Assignments and Expectations" section. The latter is completely made up; only the dates matter. The due date of Assignment 1 must be before the end of Add/Drop, and Assignment 3 must be due before the end of finals week (the last day of classes is safe). All else can go unchanged.
2. Undergrad fills out the form with their information and signs the document (by hand or with an e-signer).
3. Grad student sends form to the instructor/PI (Dr. Bohil) to be signed and then sends signed form back to the undergrad.
4. Undergrad sends completed and signed form to psych advising (room: PSY 250; email: <Psychadvising@ucf.edu>)
Due date: Signed form must be delivered to psych advising by the end of Add/Drop.

Option 2: Fill out the Volunteer Services Agreement. This brings them under the regulatory umbrella of UCF (i.e., liability insurance, ethics training compliance, etc.)
Grad student initiates form on [https://compliance.ucf.edu/enterprise-risk-management/university-volunteers/]
Filing instructions [attached]
Note: The faculty member (Dr. Bohil) must be listed as the supervisor, not a grad student. 
Note: The forms previously were good for only one semester, as of Summer 2020 they are good for a year.

### Graduate Students

## Software


You can label chapter and section titles using `{#label}` after them, e.g., we can reference Chapter \@ref(intro). If you do not manually label them, there will be automatic labels anyway, e.g., Chapter \@ref(methods).

## IRB

## Subject Recruitment

### Sona
Recruitment is done through the SONA system - see [using SONA](docs/resources/SONA Guide.pdf) for a guide to setting up and running studies using the university subject pool. 

The SONA system is administered by Dr. Chrysalis Wright, and the primary point of contact (graduate student assistant) is Mark Crisafulli. Questions should be directed to Mr. Crisafulli (psych-research@ucf.edu). 



## General advice

1. Don't get attached to any experiment (or theory); just run as many as you can!
  i) Expect to be surprised; your hypotheses will often be wrong.
  ii) We need to publish research, but desperately needing to publish something is a recipe
  for over-interpretation of results
  iii) You can mitigate this to some extent by running lots of studies.  Think of it like
  drilling for oil; its good to have a lot of wells going at once.



## Modifying this Lab Manual (Grad students only)

1. Install bookdown package in RStudio: `install.packages('bookdown')`

2. clone the Lab Manual repo onto your computer & associate the folder with a new R project in RSTudio (i.e., once you've copied the repo folder onto your computer, create a New Project in RStudio [with Git support] and assocciate it with the online repo URL as well as the folder on your computer that you just created (i.e., the clone of the online repo)).  After that you should be able to open the project in RStudio, make changes and commit/push them to the online Github repo

3. Modify only the .Rmd files that correspond to chapters.  If you need to add an image or file to link to, put it in the docs/resources/ folder. (e.g., see Sona, fNIRS examples in this book)


4. When finished, go to the Build tab (should be next to your Git tab) and select 'Build Book'.  If the book builds & launches in a local browser, everything worked correctly. 

5.  Commit changes to Git using the Git tab, and push the changes to the Github repo

Additional notes: https://bookdown.org/yihui/bookdown/



