# Writing

Some guidelines and advice on scientific writing.

## General advice

Use R Markdown
* spell checking in .Rmd
* Creating a bibliography using .bib files

## Start writing early
Write a short outline/draft of the method section when planning an experiment
* as you add details, add this to the outline (can be bullet points at first).
* IMPORTANT: If/When the experiment becomes a reality, write out the complete detailed Method Section right away - don't wait until after data collection is done and data is analyzed.  You will remember why things were done better if you write it immediately. Also power analysis should be done for every study and reported here right from the start. 

* Introduction/Lit review - same as for methods.  Work through the logic of your arguments and enumerate them, and their rationale(s) in an intro section BEFORE you run a study.  You can wait to turn this into prose as soon as the experiment becomes a reality (i.e., is running), but then you should write up a draft of the intro/lit review/experiment overview/hypotheses sections and any needed theoretical sections (e.g., plan for statistical analysis of fNIRS data, General Recognition Theory section, etc.). 
* You can also put in a lot of the references at this time, and make sure your reference section is building correctly as you go!

* Summarize all PLANNED analyses and write as much of this as you can ahead of time too.  This will be more tentative in terms of the writing, but the analysis itself should be completely knowable before starting the experiment.  
In fact - your study variables imply what analyses you'll carry out (e.g., what the variables are, the scale of the data will dictate the statistical analyses, modeling analysis planned, ANOVA details)



### misc

* every study can be boiled down to a single page summary of results; we should always create this before writing

* only write after the story is clear - the results are analyzed and evaluated and we've based our conclusions on them in the summary; then write the prose

* list: honors thesis topics we'd like to see (will consider supervising these only)

on motivation, time, & energy
> most important thing will also get the least external motivation -- research/writing
>> find a time to do this regulary; eg., 9-noon every weekday.  no distractions! (phone, email, people). 
everythign else you have to do WILL get done, because it HAS TO (nonstop external pressure to complete things): TA duties; class requirements; program requirements; talks/posters
> this is the most insidious threat to your success.  if you establish only 1 good habit let it be this: set aside time every day that is for research (whatever phase of the project you are at).  that's 15 hours/week.  i suggest 1st thing every morning to get it done.  then you can do other things with your day and relieves some pressure
> try not to make your problems other peopl'es problems: i.e., if yoiu have a big assigment, let your advisor know, but get in the habit of just planing ahead to avoid letting it disrupt your responsibilities to the lab for research.
>> even i struggle with this advice from time to time, but it has worked far better for me than anything else over the years
? do you want to know the secret to success in academics?  that's it.  i just told it to you.  not that glamorous huh?  but will you take this advice to heart and establish this habit?  only you can decide.  the biggest killers of productivity (and therefore success in academe) is distraction, time management, and dealing with stress.  establishing this habit addresses them all at once.  its the best advice i can give you. (I can lead a horse to water but I can't make it drink)  make this an iron rule, and you will thrive.


* projects/ideas
> venn diagram models
> year 1: they are a complete subset
> year 4: overlapping subsets
> never: separate circles
>> authorship: using lab resources which i'm ultimately responsible for (this includes my time and effort in advisement); i'm not in favor of you doing something on your own without an advisor;  if you want to work on a project with a different advisor, it needs my approval first.  look at it from my perspective: trying to run this lab, need people who want to learn from me.  if you decide this is not for you, let me know - maybe there's a different advisor.  best not to go to them first.  if youre not comfortable talking to me about this, talk to the program director (or above if i'm somehow the director at some point)
> authorship: i'll almost always be corresponding author; maybe not when you're at end of training.  




