# Students 

This chapter contains information for undergraduate research assistants and graduate students.  It coverse topcis related to getting started in the lab, paperwork, and program 
requirements for grad students. 


## Ph.D. Students

### HFC Program Requirements

Human Factors PhD program webpage (and link to Program Handbook)
https://sciences.ucf.edu/psychology/graduate/ph-d-human-factors-and-cognitive-psychology/


Milestones for the UCF Human Factors & Cognitive Psychology Program (for graduate students)

* Research-related class numbers
  + PSY 7919 Research 
  + PSY 7980 Dissertation 


## Undergraduate Students

### Volunteer form

THIS SECTION REDUNDANT (IF WE KEEP THE PAPERWORK IN CH 1)

1. Volunteer form
  - Before an individual can start his or her volunteer assignment, the department must complete the Volunteer Services Agreement.  Go here for details and to access the form(s):

https://compliance.ucf.edu/enterprise-risk-management/university-volunteers/

2. If you want your voluneering to appear on your transcript, you must submit a URA form.
- We need to ask the undergraduate advising office for this form
- From Director of Undergraduate Advising Karen Cox: "The process is departmentally driven.  So, the Advising Center helps with the admin side of things for the faculty.  To make it easier for you."

"You are welcome to tell students to send the forms to psychadvising@ucf.edu after they have your approval, fill out their student info, fill in the assignments, and your signature is on the form."

So it appears you need to e-mail the advising office for the form and attempt to fill it out.  Dr. Bohil can then approve it before you submit it. 

- point of contact: Karen Cox, Director of Undergraduate Advising:
https://sciences.ucf.edu/psychology/people/kox-karen/


QUESTIONS ABOUT COURSE NUMBERS, FORMS or REQUIREMENTS? 
Contact the Psychology Advising Center 
https://sciences.ucf.edu/psychology/undergraduate/advising/



COURSE CATALOG & program information
https://sciences.ucf.edu/psychology/undergraduate/ 


* Class numbers (see course catalog for descriptions)
  + PSY 4903H Honors Directed Reading I (Independent study)
  + PSY 4904H Honors Directed Reading II (Independent study)
  + PSY 4912 Directed Independent Research (Research)
    - Can enroll for 0 or 1 credit hours


UNDERGRADUATE RESEARCH 
https://our.ucf.edu/current/overview/


Enroll Students in 0-credit 4912 for the Variable Semester
See our.ucf.edu for enrollment deadline
Working with undergraduate researchers who are not already enrolled in thesis or 4912 hours this semester? Enroll students in 0-credit 4912 for the variable semester by Friday, February 21 (2020). Speak to your advising office for more information on this process.
https://our.ucf.edu/current/courses/ 

Summer Undergraduate Research Fellowship (SURF)
Applications due: March 2, 2020
SURF students participate in independent research and creative projects in collaboration with UCF Faculty during the summer. All fellows receive a $1500 scholarship. Their faculty members receive $250 supply fund.
https://our.ucf.edu/current/programs/


OUR Student Research Grants Summer Funding
Proposals due: March 27, 2020
Students can apply for grants to support research costs ($750 for individual projects or $1250 for group projects); students traveling to conduct research are eligible for up to $1250 to support travel (i.e. flights, hotel).
https://our.ucf.edu/current/programs/ 



from chrysalus re HUT course sequence;
The thesis goes like this
Directed Readings I (required; 3 credits): students work on their literature review and proposal for their study. If they are not able to finish their proposal in this semester they can register for Directed Readings II.
Directed Readings II (options; 1-3 credits): student finishes the proposal if they were not able to do so in directed readings I
Undergraduate Thesis I (required; 3 credits): students should work on collecting any needed data, analyzing data, writing up results and finish the entire thesis. They finish this with a thesis defense. If they are not able to do this in one semester they can register for Undergraduate Thesis II
Undergraduate Thesis II (optional; 1-3 credits): students finish their entire thesis if they were not able to do so in undergraduate thesis I.


